# Generated by Django 6.1.1 on 2026-09-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorsinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docphoto', models.ImageField(upload_to='')),
                ('docname', models.CharField(max_length=50)),
                ('docspecialization', models.CharField(max_length=50)),
                ('docpayment', models.FloatField(max_length=50)),
                ('doctiming', models.CharField(max_length=50)),
            ],
        ),
    ]
