# Generated by Django 6.1.1 on 2026-10-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_doctorsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=12)),
                ('patientname', models.CharField(max_length=200)),
                ('patientage', models.IntegerField(max_length=200)),
                ('patientemail', models.CharField(max_length=200)),
                ('patientphone', models.IntegerField(max_length=200)),
                ('docname', models.CharField(max_length=200)),
                ('bookingdate', models.FloatField(max_length=200)),
                ('patientproblem', models.CharField(max_length=200)),
            ],
        ),
    ]
